############################################################
# +------------------------------------------------------+ #
# |                       Заметки                        | #
# +------------------------------------------------------+ #
############################################################
#
#Автор плагина vk.com/red___tea
#
#Плагин открыто распространяется и является бесплатным
#
############################################################
# +------------------------------------------------------+ #
# |                 Основные Настройки                   | #
# +------------------------------------------------------+ #
############################################################

settings:

  #Включить дополнительное логирование в консоль?
  debug: false

  #Установить тип базы данных. Возможные типы:
  #JSON (database.json - файл), MYSQL (MySQL Data Base)
  database: JSON

  #Если вы выбрали MySQL, пожалуйста, введите данные для подключения к MySQL
  mysql:
    #Адрес подключения к базе данных
    host: '0.0.0.0'
    #Порт для подключения
    port: 3306
    #Имя базы данных
    name: 'database'
    #Имя пользователя
    user: 'username'
    #Пароль пользователя
    password: '12345'

  #Сохранять ли логи плагина в файлы?
  saveLogs: true

############################################################
# +------------------------------------------------------+ #
# |                 Настройки субкоманд                  | #
# +------------------------------------------------------+ #
############################################################
#/rev help - помощь
#/rev create [название] - начать формировать новую революцию
#/rev invite [ник] - пригласить в революцию
#/rev accept - принять текущее приглашение в революцию
#/rev kick [ник] - исключить из революции
#/rev promote [ник] - повысить до доверенного в революции
#/rev demote [ник] - понизить доверенного в революции
#/rev profile - профиль революции
#/rev deposit [кол-во] - положить деньги на баланс революции (только если есть vault)
#/rev withdraw [кол-во] - снять деньги с баланса революции (только если есть vault)
#/rev disband - расформировать революцию
#/rev leave - покинуть революцию
#/rev start - начать революцию
#/rev buypoints - купить очки прогресса революции за деньги (можно отключить)
#/rev asksupport [тег] - запросить помощь от фракции (можно отключить в конф)

#Спонсирование (можно отключить в конф)
#/rev sendsupport [токен] - начать спонсирование
#/rev stopsupport - остановить спонсирование

#Профилактика революций (можно отключить в конф)
#Раз в n дней можно выбрать только одно из:
#/rprevention checkleader [ник] - раз в 3 (n) дней проверить игрока, если он лидер революции, то расформировать
#/rprevention check [ник] - раз в 3 (n) дней проверить игрока, если он в революции, то революции -25 очков,
#но лидер ни о чем не узнает.

#Админ-команды
#/frevolutions reload - перезагрузка
#/frevolutions list - список революций
#/frevolutions disband [uuid] - распустить чужую революцию, если она не в финальной фазе
