name: FactionRevolutions
version: '${project.version}'
main: me.redtea.factionrevolutions.core.FactionRevolutions
api-version: 1.18
depend: [ Factions ]
softdepend: [ Vault, PlaceholderAPI ]
author: iRedTea
description: Add revolutions to your server!
website: https://github.com/iRedTea/FRevolutions